#!/usr/bin/env ruby
#
# (C) Copyright 2015 Hewlett-Packard Development Company, L.P.
# All rights reserved

require 'fileutils'
require 'optparse'
require 'tmpdir'

require_relative 'cli_options'
require_relative 'distribution'
require_relative 'monkey_patches/string'
require_relative 'package_management'


VERSION = '0.0.1'

EXIT_SUCCESS = 0

ERROR_GIT = 1
ERROR_DEPENDENCY = 2
ERROR_CONFIG = 3
ERROR_USAGE = 4
ERROR_BUILD = 5

LOG_FILE = Dir.pwd + '/' + File.basename($PROGRAM_NAME, '.*') + '.log'


def delete_log
  File.delete(LOG_FILE) if File.exist?(LOG_FILE)
end

def pull_repo(branch, repo, tmp_dir)
  puts "Pulling #{branch} branch from the #{repo} repo."
  `git clone \
    --recursive \
    --depth=1 \
    --branch #{branch} \
    #{repo} \
    #{tmp_dir} \
    &>> #{LOG_FILE}`
  fail_if_error(ERROR_GIT, 'Error pulling from git')
end

def fail_if_error(exit_code, message)
  unless $?.success?
    puts "#{message}. Check #{LOG_FILE} for more details."
    exit exit_code
  end
end

def generate_config
  `(./autogen.sh && ./configure) &>> #{LOG_FILE}`
  fail_if_error(ERROR_CONFIG, 'Error setting up the configuration')
end

def determine_distro(package_manager)
  if package_manager == :yum
    return RedHat.new
  else
    return Debian.new
  end
end


cli = CliOptions.new
package_management = PackageManagement.new(cli.no_debs)
distro = determine_distro(package_management.package_manager)
delete_log
pull_repo(cli.branch, cli.repo, cli.tmp_dir)
Dir.chdir(cli.tmp_dir) do
  distro.install_dependencies
  generate_config
  distro.build_packages
end
